[package]
name = "ninput"
version = "0.1.2"
edition = "2021"
description = "helper input function that behaves just like in python"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
